version: '2'
services:
    odsupercomponent:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        network_mode: "host"
        restart: always
        volumes:
        - .:/opt/miniature.data
        command: "/opt/od4/bin/odsupercomponent --cid=140 --verbose=1 --configuration=/opt/miniature.data/configuration"

    proxy-miniature-pwm-motor:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        depends_on:
        - odsupercomponent
        network_mode: "host"
        restart: always
        privileged: true
        volumes:
        - /sys/:/sys/
        - /dev/:/dev/
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-pwm-motor --cid=140 --freq=50 --id=1"

    V2V:
        image: cyka7
        network_mode: "host"
        depends_on:
        - device-ultrasonic-srf08-front
        restart: always
        command: "/opt/V2V.Service --freq=5 --ip=192.168.1.237"

    device-ultrasonic-srf08-front:
        image: chalmersrevere/opendlv-device-ultrasonic-srf08-armhf:v0.0.6
        network_mode: "host"
        privileged: true
        volumes:
          - /dev/i2c-1:/dev/i2c-1
        command: "/usr/bin/opendlv-device-ultrasonic-srf08 --dev=/dev/i2c-1 --bus-address=221 --cid=141 --freq=5 --id=0"

